### ISSUE TITLE
Userstory 1 - Create Header

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project#2]
## Value Proposition

**As a** User,
**I want to** see the Header of the WebApp and its Logo and a Link to Facebook,
**so that** I can see that I am in the web from Havana Bikes and I am able to go to its facebook profile
​

## Description

![userstory-1_header](https://user-images.githubusercontent.com/53151968/213435979-b3fd7cf2-6fd0-4138-a83e-5d708befaa5c.png)

## Acceptance Criteria

- [ ] The Header is displayed
- [ ] The logo is displayed on the Header
- [ ] The link to facebook is displayed on the Header
      ​

## Tasks

- [ ] Create the Header
- [ ] Create the Logo
- [ ] Create the Link to facebook
      ​

## Complexity

XS

**Comment by SaschaRadojkovic** [comment]
i think it is ok as the first small UserStory, maybe mine is to lager yet ;)

**Comment by NikRoe** [comment]
Hey Yuri,

I don't see too much value for a user having a header and a link to facebook at the very beginning.

I would suggest you start your project by displaying a static list of bikes.

On a more general note: Your value proposition should be short and concise. You should not mention the single components you intend to implement with that user story. That is something you do in your tasks and acceptance criteria

**Comment by YuriPadilla** [comment]
Thanks Niklas, I will try it again...
