### ISSUE TITLE
Userstory ? - Create the Navigation Bar (NavBar)

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project#3]
## Value Proposition

**As a** User,
**I want to** see the NavBar with the nav icons and I want every icon to get highlighted when clicking on it,
**so that** I can navigate between the different pages and see in which page I am actually.
​

## Description

![Bildschirmfoto 2023-01-19 um 15 19 57](https://user-images.githubusercontent.com/53151968/213466288-d4b2938a-d70e-401b-a317-312b607363fc.png)

​

## Acceptance Criteria

- [ ] The NavBar is displayed
- [ ] The Navigation Icons are symmetrically displayed on the NavBar
- [ ] The Navigation Icons get highlighted with a click if not highlighted and vice versa
- [ ] ...
      ​

## Tasks

- [ ] Create a new folder for the necessary icons and download them into the created folder
- [ ] Create the NavBar
- [ ] Create an area on the NavBar for every icon
- [ ] Display the icons on their respective area on the NavBar
- [ ] Code the logic so that the icons get highlighted with the click and vice versa
      ​

## Complexity

M
