### ISSUE TITLE
Userstory ? - Create the folder structure in Next.js (/pages/... etc)

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project#4]
## Value Proposition

**As a** User,
**I want to** be able to change between pages in the WebApp,
**so that** I can see the content of the different pages.
​

## Description

![Bildschirmfoto 2023-01-19 um 15 51 49](https://user-images.githubusercontent.com/53151968/213474212-929b8bc1-6425-4aa3-b7e1-a3642ddbcd6a.png)
​

## Acceptance Criteria

- [ ] Display "Hello from Home" when clicking the icon "Home",
- [ ] Display "Hello from Gallery" when clicking the icon "Gallery",
- [ ] Display "Hello from Route Maps" when clicking the icon "Route Maps",
- [ ] Display "Hello from More" when clicking the icon "More",
      ​

## Tasks

- [ ] Create the structure folder in: /pages,
- [ ] Create the respective index.js files for every page,
- [ ] Add content to every index.js ("Hello from...", etc),
- [ ] Add the necessary Links to be able to display every page.
      ​

## Complexity

S
