### ISSUE TITLE
Userstory 1 - Create the price info and the list of bikes 

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project#5]
## Value Proposition

**As a** User,
**I want to** see the price and a list of bikes,
**so that** I can see which of them I will choose.
​

## Description

![Image](https://user-images.githubusercontent.com/53151968/213703927-4356a850-f859-42b6-8082-a3bcd69b81ed.png)
​

## Acceptance Criteria

- [ ] The prices are displayed,
- [ ] The user should be able to see a preview of some bikes and the "...Show more" link to "Bikes",
- [ ] On clicking "...Show more" the user should be able to navigate to the page "Bikes" where a list of bikes is displayed.
- [ ] On clicking "Home", the user should be able to navigate back to "Home" from the page "Bikes".
      ​

## Tasks

- [x] Create the Component to display the prices and other infos like open / close time, etc... in a section "Price",
- [x] Create a json file with an array of all the bikes, with characteristics and link to their respectively foto,
- [x] Create the Component "BikesPreview" with 2 or 3 fotos as a preview and a link to a new page "Bikes",
- [x] Create the new page "Bikes", 
- [x] Create a new component "BikesList" and return it in the page "Bikes", 
- [x] In the component "BikesList", map over the array of all the bikes and return the list of the bikes in this page "Bikes",
- [x] Create the link to get back to "Home",
- [x] Create the Component for the Header.
      ​

## Complexity

L

**Comment by AstridOttmann** [comment]
It's not quite clear, what I will see in the list: a picture or also additional information about the bikes (Acceptance Criteria)

**Comment by YuriPadilla** [comment]
Thanks Astrid, I will update it.

**Comment by doemser** [comment]
Try to be much more specific with your AC's, here are a few examples:

- The user should be able to navigate to a page where a list of bikes and their respective prices are displayed.
- The prices should be clearly visible next to each bike.
- The user should be able to sort the list of bikes by price.
- The user should be able to filter the list of bikes by price range.
- The user should be able to select a bike from the list and proceed to rent it.

If I were to try to implement your user-story, I would still be missing some important information to make it become what you envision. These are exactly the points your AC should cover.

**Comment by YuriPadilla** [comment]
Hey Dominik!!! Many thanks for your review and tips!!! :) I've already corrected some aspects.

- About the prices: There is only one price, it is 15 € per bike per day, that's why the price is only displayed on the "Home" page.
- About the filter: I wanted to do it in another User Story, because I find it a little bit too much for the first User Story.
- About selecting a bike from the list: I wanted it also to do it in another User Story

What do you think about it??? Thanks again and many greetings to you.

**Comment by doemser** [comment]
I have only given you examples that show how precisely acceptance criteria should be formulated. Regarding the prices: Your acceptance criteria says "The prices are displayed" and that's the point, to be more precise about what you want to do, so that everybody understands what you want to do.
