### ISSUE TITLE
Userstory 3 - Add list of bike parts

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project#6]
## Value Proposition

**As a** User,
**I want to** see a list of bike parts,
**so that** I can see which of them I will choose.
​

## Description

![Image](https://user-images.githubusercontent.com/53151968/213729728-f2f54faa-bae0-4087-bee9-ea668af3edb2.png)

## Acceptance Criteria

- [ ] The user should be able to see a preview of some bike parts and the "...Show more" link to "Bikes",
- [ ] On clicking "...Show more" the user should be able to navigate to the page "Bike Parts" where a list of bike parts is displayed.
- [ ] On clicking "Home", the user should be able to navigate back to "Home" from the page "Bikes".
      ​

## Tasks

- [x] Create a json file with an array of all the bike parts, with characteristics and link to their respectively foto,
- [x] Create the component "BikePartsPreview" with 2 or 3 bike parts fotos displayed as a preview and a link "...Show all" to the new page "BikeParts",
- [x] Add this component "BikePartsPreview" to "Home" with the bike parts list as prop,
- [x] Create the new page "BikeParts",
- [x] Create a new component "BikePartsList" and return it in the page "BikeParts",
- [x] In the component "BikePartsList", map over the array of all the bike parts and return the list of the bike parts in this page "BikeParts",
- [x] Create the link to get back to "Home".
      ​

## Complexity

M

**Comment by NikRoe** [comment]
Hi Yuri,

I have some notes / suggestions / questions regarding this user story:
- Will there be an option to navigate back to the home page when on the bike parts page? (A back link might do) If you choose to add such a link, please specify this in your acceptance criteria and tasks
- you don't need to mention that you download the fotos
- will you be using an existing component to display the information of your bike parts? Please be specific about this
- the value proposition suggests that you are able to rent bike parts, though for the moment you are just able to see / browse bike parts

I hope this helps :)

**Comment by YuriPadilla** [comment]
Hey Niklas!!! Thank you so much again for the review and tipps...!!!  :)  :) :) 

I have already updated this User Story with your tipps. I hope it is OK now.

I'm looking forward to getting another review from you (or the other coaches). Thousands thanks to you!!! :)

**Comment by RobinWitt** [comment]
To me that User Story looks very well-rounded now and seems to have a good scope and complexity.
The only thing that is not so clear to me yet is the intended behavior of the 'preview' products. 
Do you want them to be clickable so that the User can access a Details Page of that Bike Part? 
Do you want the 'preview' products to always be the same or be random?
If you clarify that in your User Story, I think you are good to go!

**Comment by YuriPadilla** [comment]
Thank you Robin!!! 👍

The Idea ist to make it clickable and make it so, that the user can slide this preview to both side... and some things more, but I will let it for later for other User Stories.

Thanks again for your review and many greetings to you!!! 😀 👋
