### ISSUE TITLE
Userstory 2 - Add contact info

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project#7]
## Value Proposition

**As a** User,
**I want to** see the contact info,
**so that** I can contact them for booking a bike and for asking questions.
​

## Description

![Image](https://user-images.githubusercontent.com/53151968/213783191-8bc5c1d6-449e-44dd-9fa7-39c9e8291f46.png)

## Acceptance Criteria

- [ ] The contact information is displayed,
- [ ] A button "Contact us" is displayed,
- [ ] The button "Contact us" displays a form in a new page "Contact us",
- [ ] The form contains: input "name" (required), input "email" (required), text-area "message" (required), 
- [ ] The form contains also: a submit button "Send", a button "Cancel" and a button "<- Back" to get back to "Home",
- [ ] The button "Send" sends the message to Havana Bikes, get the page "Home" again, and a confirmation is showed.
- [ ] The confirmation display the message: "your message was sent",
- [ ] The button "Cancel" gets back to "Home" without sending the message.
      ​

## Tasks

- [x] Create the Component "ContactInfo" with the necessary contact information and include it in "Home",
- [x] Create component "Button" and... 
- [x] use it to add the button "Contact us" in the Component "ContactInfo"
- [x] Add logic to "Contact us" to open a new page "ContactUsPage",
- [x] Create the page "ContactUsPage", where a form will be displayed,
- [x] Create component "ContactUsForm" and use it in the page "ContactUsPage",
- [x] Add to the form in page "ContactUsPage":  input "name" (required), input "email" (required), textarea "message" (required), a submit button "Send" and a button "<- Home".
- [x] Add logic and functionality to the button "<- Back",
- [x] Add logic and functionality to the button "Send" (first just to get a notification that the message was sent. I'll work some day later on the logic to really send an email with _"SendGrid"_).
​

## Complexity

L

**Comment by NikRoe** [comment]
Hi Yuri,

you should split this user story into smaller user stories:
- one user story for the bike details page
- one user story for the contact form

Since this user story is title "add contact info" for the moment, I will leave some notes regarding the contact form:
- please specify if any form of form validation is applied (like requiring certain input fields etc.) and what this will imply for a user using your app
- do you want the contact form to be always visible or only when a button was clicked previously or even on a separate page? If so, please specify
- after submitting the contact form, do you want users to see a confirmation?

I hope this already helps! :)

**Comment by YuriPadilla** [comment]
Hey Niklas!!! Thank you so much for the review and the tipps, it was very helpful...!!!

I have already updated the User Story with your tipps. I hope it is OK now.

I look forward to a review from you or the other coaches. Many thanks to you!!!  :)

**Comment by NikRoe** [comment]
Hi Yuri,

the scope of the user story and the user story itself look really nice!

Comparing the wireframe and your acceptance criteria / tasks, I was wondering whether the contact form is on a new page. It at least appears to be that way, though I might be mistaken. So this is just a question to you, whether it's part of the home page and opens on button click?
If it is on a separate page you should mention this and also think about how the user can navigate back to the home page (maybe just a back button)

And I have another question: Do you feel like it is intuitive for a user to click on a cancel button and be redirected to a different page? I would argue that it isn't and leave that button out. 
Instead I would have a designated back button to navigate back to the home page.

Long text, but actually only some minor adjustments that need to be done! 🙌

**Comment by YuriPadilla** [comment]
Hey Niklas! Thanks again!!! 😀👍

I wanted the "Contact us" form to be displayed in the same "Home" page, but over it... in a way that the user  is just  able to write the message and send it (or cancel it) and then he/she just continue in "Home" after clicking "Send" or "Cancel". But now that I think very carefully about it, I think you are right and it is better to do the form in a separate page and to have the possibility to keep saved what is written, falls the user wants to go back  to "Home" to see some info and then continue writing the message.

So... I will update it with your tipps.

Thank you again!!!! And I hope to get another review from you!!! 😀 👍 👋
