### ISSUE TITLE
Userstory 4 - Add details page for every bike

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project#8]
## Value Proposition

**As a** User,
**I want to** see the details of a selected bike,
**so that** I can see if I want to rent it.
​

## Description

Clicking on a picture of a bike opens a details page and shows the foto and characteristics of that bike.

![Image](https://user-images.githubusercontent.com/53151968/214529246-5df8f7fb-6eff-4490-b52d-6d5fa7b2015e.png)

## Acceptance Criteria

- [ ] Clicking  on a picture opens the page "Details"
- [ ] A history of the links "Home", "Bikes" and "Details" is displayed.
- [ ] A picture of the selected bike is displayed.
- [ ] The details of the selected bike is displayed.
      ​

## Tasks

- [ ] Add a dynamic page [id].js to show the details of the selected bike.
- [ ] Add functionality so that when clicking on a picture, it opens the dynamic details page. You can use "useRouter", ...etc.
- [ ] In [id].js add the history links (with the respective links) as shown in the Excalidraw picture.
- [ ] Add the foto of the selected bike.
- [ ] Add the details of the selected bike.
​

## Complexity

M

**Comment by RobinWitt** [comment]
Hi Yuri, nice user story. However, you should not at the button "add to basket" if it is not working yet.
Implementing the button and its functionality could be a well-rounded user story on its own.

**Comment by NikRoe** [comment]
Hi Yuri,
nice work!
