### ISSUE TITLE
Userstory 5 - Create functionality to add products in the basket

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project#9]
## Value Proposition

**As a** User, 
**I want to** to be able to add bikes to the basket,
**so that** I can book them later.
​

## Description

When the page "Details" is displayed and the user click on "Add to basket", the current bike will be added to the basket and the previous page "Bikes" will be showed again with the particularity that the product added to the basket won't be there on page "Bikes" anymore. Also the icon which represents the basket shows the number of products... as shown on the Excalidraw picture. Also when there are products on the basket, the basket icon will be showed on every page.

![Bildschirmfoto 2023-01-24 um 22 59 50](https://user-images.githubusercontent.com/53151968/214430666-0f43bfff-c911-4e7e-ad82-01e62e139c37.png)
​

## Acceptance Criteria

- [ ] The basket icon is displayed on the "Details" page on top - right,
- [ ] The button "Add to basket" is displayed,
- [ ] Clicking on "Add to basket" redirects to the page "Bikes",
- [ ] The selected bike won't be displayed on "Bikes" anymore,
- [ ] The icon for Basket shows the number "1" after added one bike.
      ​

## Tasks

- [ ] Add the button "Add to basket" in the position bottom-right,
- [ ] Use the "useLocalStorageState" to keep the array of the bike local in the browser,
- [ ] Create the array for the basket to save there the selected bike, save this array in local storage (use "useLocalStorageState"),
- [ ] Create the component Basket which will be the icon for the basket, you can use styled components for it.
- [ ] Set this component in the position top-right on the page "Details" (later also on every page when more selected products),
- [ ] Add functionality to the button "Add to basket"(Add the bike to the basket and shows page "Bikes"):
- [ ] Create the function to handle "Add to basket" and...
- [ ] ...add functionality so that the respective selected bike is added to the array of the basket saved in the local storage,
- [ ] ...add functionality so that the respective selected bike is deleted from the array of the bikes saved in the local storage.
​

## Complexity

XL

**Comment by RobinWitt** [comment]
I think XL is the right complexity level for this story :D 
Just put the "add to basket" button from US 4  in here and you are good to go, in my opinion.

**Comment by mbosselmann** [comment]
Hi Yuri,
I like your user story! 
You rock! 🪨

Happy hacking! :octocat:
